---
name: On Merge

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/erenfro/bloghugo
  PACKAGE_NAME: bloghugo

jobs:
  release-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b32f140b0c872d58512e0a66172253c302617b90

      - name: Build
        uses: ./.github/actions/docker-image
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          latest: true

      - name: Delete old containers
        uses: actions/delete-package-versions@0d39a63126868f5eefaa47169615edd3c0f61e20 # v4
        with:
          package-name: ${{ env.PACKAGE_NAME }}
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 2
